### ISSUE TITLE
Is there a way to add cookies to the request?

### ISSUE THREAD

**Issue by kafisatz** [bluesmoon/CurlHTTP.jl#3]
might be better to discuss this here instead of https://github.com/JuliaWeb/LibCURL.jl/issues/103

**Comment by bluesmoon** [comment]
Cookies are just HTTP headers, so you will need to add your correctly formatted cookies to the `CurlEasy` handle using [`curl_add_headers`](https://bluesmoon.github.io/CurlHTTP.jl/dev/#CurlHTTP.curl_add_headers-Tuple{CurlEasy,%20Vector{String}})

There is currently no higher level API, nor is there a cookie jar that will store cookies per domain and send them automatically on subsequent requests.

**Comment by kafisatz** [comment]
thanks. I will try this out. 

I know very little about HTTP, but I noticed that, e.g. HTTP.jl, has different keywords for headers and cookies, thus I am not quite sure whether cookies are just headers.

**Comment by bluesmoon** [comment]
Yes, it's just a header (header name is `Cookie`). HTTP.jl is a higher level API that probably also maintains a cookie jar.

For the cookie value, you will have multiple cookies as a `;` separated list of `name=value`. If the value has special characters, then it should be enclosed in quotes.  eg:

`Cookie: foo=bar; foo2="hello world"; name="bluesmoon"`

**Comment by kafisatz** [comment]
Thanks. This works like a charm.
Appreciate the explanation to add 'Cookie' as header name!.
